#! /usr/bin/env php
<?php

include dirname(__FILE__) . '/vendor/autoload.php';

include dirname(__FILE__) . '/includes/base/Autoloader.php';

\AcquiaUtil\Base\Autoloader::register();

$command = $argv[1];

$params = array_slice($argv, 2);

$class = '\AcquiaUtil\Commands\\' . $command;

if (!class_exists($class)) {
  var_dump("Sorry, that command does not exist.");
}

// TODO: Allow for sub-commands.
$result = call_user_func($class . '::factory', $params);

var_dump($result);
