#! /usr/bin/env php
<?php

include dirname(__FILE__) . '/vendor/autoload.php';

include dirname(__FILE__) . '/includes/base/Autoloader.php';

\AcquiaUtil\Base\Autoloader::register();

$command = explode('::', $argv[1]);

if (empty($command[1])) {
  $command[1] = 'run';
}

$params = array_slice($argv, 2);

$class = '\AcquiaUtil\Commands\\' . $command[0];

if (!class_exists($class)) {
  var_dump("Sorry, that command does not exist.");
}

$class = call_user_func($class . '::factory', $params);

// TODO: Allow command class to handle the "output" in pretty formats.
try {
  $result = $class->{$command[1]}();
  \cli\out(print_r($result, true));
} catch (\Exception $e) {
  var_dump($e->getMessage());
}
